### PR TITLE
Remove unneeded files

### PR DESCRIPTION
**Pull request by JakobDev**
This files were copied from the main repo and are not needed. Especially the external-data-checker workflow runs each hour.

### CODE REVIEW

**Comment by CodeDoctorDE** [comment]
Nice thanks. Can you help me with the external-data-checker? It doesn't update automatically

**Comment by JakobDev** [comment]
> Can you help me with the external-data-checker? It doesn't update automatically

This workflow does not belong here. I have removed the file in this PR to stop this.

**Comment by CodeDoctorDE** [comment]
Yes I know, but the external data checker in `dev.linwood.butterfly.json` doesn't work either.

**Comment by JakobDev** [comment]
You don't use the external data checker in your manifest.

**Comment by JakobDev** [comment]
Should I make a PR to add f-e-d-c to your manifest?

**Comment by CodeDoctorDE** [comment]
Yes, that would be helpful.
I have also a nightly version, it would be cool if all pre releases, that starts with `v`, can be added to a beta branch.

**Pull request merged**
